### ISSUE TITLE
Loader not working with SDXL

### ISSUE THREAD

**Issue by cavit99** [LucianoCirino/efficiency-nodes-comfyui#63]
<img width="853" alt="Screenshot 2023-07-28 at 10 42 07" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/35897738/4bcbf3c8-038c-49fd-847a-f344c439f0bc">
<img width="1513" alt="Screenshot 2023-07-28 at 10 41 58" src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/35897738/8c3e5581-68fc-491f-a7e2-f44334f88850">

**Comment by lhovav** [comment]
Same with me

**Comment by LucianoCirino** [comment]
Will investigate

**Comment by LucianoCirino** [comment]
This should now be fixed by comit https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/1ed9e0e1a2293a57930ea055f98f306589759317. Please test and close if good :)

**Comment by lhovav** [comment]
Hi, @LucianoCirino thanks for the quick fix!
although I didn't open the ticket I can confirm it does fix the issue, But I'm getting this error when trying to use the refiner in a 2nd pass:
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/118633533/d0473912-002e-4918-9f39-9e5c3d556224)

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/118633533/79387053-4072-457f-a286-0764cc52d313)

Probably something that I'm doing wrong..

**Comment by Pat-Petereit** [comment]
Can confirm, i have the same error. It doesnt matter if i use a efficent or default sampler in the second step. No problem if i use a defualt ksampler as first step and efficient ksampler as second

**Comment by cavit99** [comment]
> This should now be fixed by comit [1ed9e0e](https://github.com/LucianoCirino/efficiency-nodes-comfyui/commit/1ed9e0e1a2293a57930ea055f98f306589759317). Please test and close if good :)
> 
> ![image](https://user-images.githubusercontent.com/112517630/256962661-0bd5bed9-eed6-4d4b-bf36-7d4f25713afd.png)

Thanks so much for attending to it. Any chance refiner can also be fixed on 2nd pass so we can close? Love your work

**Comment by Pat-Petereit** [comment]
[Bugjson.zip](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12207644/Bugjson.zip)

Also this is the workflow which creates the error (you may need to change checkpoint path)

**Comment by tkoenig89** [comment]
> Hi, @LucianoCirino thanks for the quick fix! although I didn't open the ticket I can confirm it does fix the issue, But I'm getting this error when trying to use the refiner in a 2nd pass: ![image](https://user-images.githubusercontent.com/118633533/256965670-d0473912-002e-4918-9f39-9e5c3d556224.png)
> 
> ![image](https://user-images.githubusercontent.com/118633533/256965744-79387053-4072-457f-a286-0764cc52d313.png)
> 
> Probably something that I'm doing wrong..

I had this issue already, i figured out that you cannot use the conditioning from the base model, with the refiner sampler. You need to encode the prompts with the clip from the refiner to make the refiner-sampler work. Hope this helps.

**Comment by tkoenig89** [comment]
[fixedjson.zip](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12209951/fixedjson.zip)

Here is your workflox, but fixed. But as i understand this is not really what the 'original' SDXL-comfy workflow does. It somehow leaves noise in the image generated from the base model, and letting the refiner finish of. Here we just finish something with the base, than add new noise before refining. But i guess this is not a topic for this bug, as the issue itself is solved - i guess.

**Comment by lhovav** [comment]
Hi @tkoenig89 
Thanks for the help!
Can confirm that it works the way you suggested, I still don't know if its something that can be fixed (or should) - it feels more efficient to continue the conditions from one efficient loader, But obviously its easy to say than done...
Thanks again!

**Comment by LucianoCirino** [comment]
> 
I was unable to replicate error. Maybe I fixed it accidently with one of my recent commits. Unless I am doing something wrong?

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/1cee5715-e95e-4986-909c-4593ba9c2902)
[tsc_test1.zip](https://github.com/LucianoCirino/efficiency-nodes-comfyui/files/12211064/tsc_test1.zip)

**Comment by lhovav** [comment]
Hi @LucianoCirino , Thanks for taking care of it.
In your example you are using 3 Ksamplers, in mine, I used only 2.
Full work flow:
![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/118633533/5bcbf49c-e6b3-49f6-9712-18ef9f3f8247)

**Comment by tkoenig89** [comment]
@LucianoCirino i dont't think you fixed it, because it might not be a bug, but how SDXL works. Your workflow seems (and i'm not really a pro here :) ) flawed in the regards, that you use the base model in your refiner sampler (flows through the first sampler to the refiner sampler). Thats the reason why you don't get the 'mat and mat2' error. If you would use the loaded refiner model, you will get the same error, as the encoded prompts (CONDITIONINGS) will not work with the refiner. I guess there are same matrixes (mat1, mat2) that have different dimension for base and refiner. I find it hard to explain, as this is something i did not find anywhere else and just 'made' up in my own mind :D. 

I tried to explain this in one of my post above. If you want to use the refiner the 'SDXL' way, you may need to extend your EfficientSampler so you can enable 'leftover noise' in the base, and disable 'add noise' on the refiner sampler (see comfy examples for SDXL: https://comfyanonymous.github.io/ComfyUI_examples/sdxl/)

**Comment by lhovav** [comment]
did he use the refiner? the models in @LucianoCirino workflow is only the base model...

**Comment by tkoenig89** [comment]
you are right. My brain tricked me in seeing the refiner checkpoint in the top loader, for some reason. Maybe because i had the refiner in there for my workflow. But there is still the point about, how to do the SDXL workflow with the efficient nodes.

**Comment by LucianoCirino** [comment]
> @LucianoCirino i dont't think you fixed it, because it might not be a bug, but how SDXL works. Your workflow seems (and i'm not really a pro here :) ) flawed in the regards, that you use the base model in your refiner sampler (flows through the first sampler to the refiner sampler). Thats the reason why you don't get the 'mat and mat2' error. If you would use the loaded refiner model, you will get the same error, as the encoded prompts (CONDITIONINGS) will not work with the refiner. I guess there are same matrixes (mat1, mat2) that have different dimension for base and refiner. I find it hard to explain, as this is something i did not find anywhere else and just 'made' up in my own mind :D.
> 
> I tried to explain this in one of my post above. If you want to use the refiner the 'SDXL' way, you may need to extend your EfficientSampler so you can enable 'leftover noise' in the base, and disable 'add noise' on the refiner sampler (see comfy examples for SDXL: https://comfyanonymous.github.io/ComfyUI_examples/sdxl/).
> 
> One thing i found bad about this SDXL workflow at the moment: you need to provide the prompts twice for the correct encodings to happen.

I apologize for the misunderstanding and now see the issue. 

![image](https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/a6fe46be-e04a-45b1-873b-5bcbb4c2fc4b)

Summary:
To have the refiner ksampler step to work, you you must encode your text conditioning to the refiner using the refiner's clip.

I am now closing this topic.

**Comment by tkoenig89** [comment]
@LucianoCirino not sure if this is just me, but after i reinstalled comfy ui on a different disk and installed efficient nodes, i get the pooled_output error again. This seems related to the loader, as using the normal comfy nodes just works fine with SDXL checkpoints. Maybe the fix, that worked before has been overriden by a different change/fix?

**Comment by LucianoCirino** [comment]
Updated repo, Efficiency nodes now support a simpliefied SDXL workflow. XY Plot compatible aswell.

<img src="https://github.com/LucianoCirino/efficiency-nodes-comfyui/assets/112517630/e1f3c472-39e0-4bf8-b4a3-00c10687c78c" width="720">
